name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
          
      - name: Routine
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: celesica
          base: ""
          config_timezone: Asia/Manila
          config_octicon: yes
          template: classic
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_languages_threshold: 0%
          plugin_isocalendar: yes
          
      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          filename: habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: celesica
          base: ""
          config_timezone: Asia/Manila
          config_octicon: yes
          template: classic
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: wakatime.svg
          token: ${{ secrets.WAKATIME_TOKEN }}
          user: celesica
          base: ""
          config_timezone: Asia/Manila
          config_octicon: yes
          template: classic
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, languages-graphs, editors, editors-graphs
